export const API_URL =
  process.env.NODE_ENV === "development"
    ? "http://localhost:8000/api"
    : "https://soccerstats-api.onrender.com/api";

export const EventTypes = [
  "50/50",
  "Bad Behaviour",
  "Ball Receipt*",
  "Ball Recovery",
  "Block",
  "Carry",
  "Clearance",
  "Dispossessed",
  "Dribble",
  "Dribbled Past",
  "Duel",
  "Foul Committed",
  "Foul Won",
  "Goal Keeper",
  "Half End",
  "Half Start",
  "Injury Stoppage",
  "Interception",
  "Miscontrol",
  "Offside",
  "Pass",
  "Player Off",
  "Player On",
  "Pressure",
  "Referee Ball-Drop",
  "Shield",
  "Shot",
  "Starting XI",
  "Substitution",
  "Tactical Shift",
] as const;
export type EventType = (typeof EventTypes)[number];

export const EventTypeToLabel: Record<(typeof EventTypes)[number], string> = {
  "50/50": "50/50s",
  "Bad Behaviour": "Bad Behaviours",
  "Ball Receipt*": "Ball Receipts",
  "Ball Recovery": "Ball Recoveries",
  Block: "Blocks",
  Carry: "Carries",
  Clearance: "Clearances",
  Dispossessed: "Dispossesseds",
  Dribble: "Dribbles",
  "Dribbled Past": "Dribbled Past",
  Duel: "Duels",
  "Foul Committed": "Fouls Committed",
  "Foul Won": "Fouls Won",
  "Goal Keeper": "Goal Keeper",
  "Half End": "Half End",
  "Half Start": "Half Start",
  "Injury Stoppage": "Injury Stoppages",
  Interception: "Interceptions",
  Miscontrol: "Miscontrols",
  Offside: "Offsides",
  Pass: "Passes",
  "Player Off": "Player Offs",
  "Player On": "Player Ons",
  Pressure: "Pressures",
  "Referee Ball-Drop": "Referee Ball-Drops",
  Shield: "Shields",
  Shot: "Shots",
  "Starting XI": "Starting XIs",
  Substitution: "Substitutions",
  "Tactical Shift": "Tactical Shifts",
};
